// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import path from 'node:path';

export default defineConfig({
  schema: path.join('prisma'),
  migrations: {
    path: 'prisma/migrations',
    seed: 'node prisma/seeds/index.js',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
